### PR TITLE
Misc Supreme Optimizations 

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
This PR:
- Fixes some Misspellings
- Optimizes TechMutation & TechRobotic by removing unnecessary .clone() calls from SlimefunItemStack
- Optimizes TechGenerator by adding the tier & type of MobTech to its NBT data, to remove the laggy SlimefunItem#fromItem call. If the item does not have the relevant NBT it will fallback to the SlimefunItem#fromItem and if it is a MobTech it will add the relevant NBT data.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
Just need to do the testing for this, tried to test but I honestly don't know how MobTech works in supreme 😅

**Comment by RelativoBR** [comment]
@JustAHuman-xD Tests carried out, both the old items and the new ones are working correctly, but they are no longer accumulating, which is common whenever there is an attribute change in the items, for this case there is already a contour action with the item convert machine that resets attributes to initial value.

image
image
image

**Review by RelativoBR — APPROVED** [review]

**Comment by JustAHuman-xD** [comment]
Alright is there anything else you think is necessary before merging?

**Comment by JustAHuman-xD** [comment]
Also can you send the full timings report for those screenshots of sf timings, if you have it anyway?

**Comment by RelativoBR** [comment]
I don't have this complete report (I don't know how to generate it either), I imagine that everything is fine for the merge, the change is as expected and there are no impacts for players, except for the union of old and new items in the same stack (something inevitable).

**Pull request merged**
