### PR TITLE
Fix error when using the latest version of bukkit/paper caused by obsolete methods...

### PR DESCRIPTION
**Pull request by DeuzivanLima**
# Details
This PR fixes an error that occurs when using the latest versions of the bukkit API, and updates some dependencies.

# Versions
- Minecraft: 1.20.4
- Paper: 1.20.4-484
- OpenJDK: 17.0.10 2024-01-16

# Paper
I used the paper as a reference to correct it, and after the correction the plugin started to work normally, without any warnings or errors.

# Screenshots
2024-04-18-100034_1920x1080_scrot

### CODE REVIEW

**Comment by Boomer-1** [comment]
supreme already works on the latest versions of minecraft, 1.20.4. you have to download the latest version from https:\\blob.build

**Comment by ybw0014** [comment]
this will break the compatibility below 1.20.2 as `Registry.EFFECT` is added on 1.20.3.

**Comment by DeuzivanLima** [comment]
**When I use these versions:**
- PaperMC 1.20.4-484
- Minecraft 1.20.4
- Slimefun4 - Build 37 (797249fd)
- Supreme - DEV 29 (git f9e70).jar



Causes this error.

```log
[16:47:46 INFO]: [Supreme] Enabling Supreme vDEV - 29 (git f9e70053)
[16:47:46 INFO]: [Supreme] ########################################
[16:47:46 INFO]: [Supreme]       Supreme 2.0  - By RelativoBR
[16:47:46 INFO]: [Supreme] ########################################
[16:47:46 INFO]: [Supreme] Auto Update: enable
[16:47:46 INFO]: [Supreme] Loaded language Supreme: en-US
[16:47:46 INFO]: [Supreme] Legacy SupremeExpansion IDs: disable
[16:47:46 ERROR]: Error occurred while enabling Supreme vDEV - 29 (git f9e70053) (Is it up to date?)
java.lang.InstantiationError: org.bukkit.enchantments.EnchantmentWrapper
	at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.getEnchants(EnchantsAndEffectsUtil.java:123) ~[Supreme - DEV 29 (git f9e70).jar:?]
	at com.github.relativobr.supreme.util.EnchantsAndEffectsUtil.addGearBasicEnchants(EnchantsAndEffectsUtil.java:104) ~[Supreme - DEV 29 (git f9e70).jar:?]
	at com.github.relativobr.supreme.gear.AbstractWeapons.setup(AbstractWeapons.java:26) ~[Supreme - DEV 29 (git f9e70).jar:?]
	at com.github.relativobr.supreme.setup.MainSetup.setup(MainSetup.java:26) ~[Supreme - DEV 29 (git f9e70).jar:?]
	at com.github.relativobr.supreme.Supreme.onEnable(Supreme.java:172) ~[Supreme - DEV 29 (git f9e70).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-484]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-484]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-484]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-484]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-484]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**This occurs in 1.20.4 even if I use the `release` versions.**
- Slimefun4 - Build 37 (797249fd)
- Supreme - DEV 29 (git f9e70).jar

**Comment by Boomer-1** [comment]
as I said this has already been fixed. you do not have the latest version of supreme. as already mentioned you must download it from https://blob.build

**Comment by Boomer-1** [comment]
please close this PR as it is not needed

**Pull request closed without merging**
