### PR TITLE
Transporters

### PR DESCRIPTION
**Pull request by scorninpc**
Enable transporters for all recipe

https://github.com/user-attachments/assets/e1ae899b-b5e3-46dd-870a-fe98e59a2d08

### CODE REVIEW

**Comment by Boomer-1** [comment]
seems your video is showing the machine working perfectly. what's the issue? also you only need to put 1 item in the pusher not 64

**Comment by scorninpc** [comment]
> seems your video is showing the machine working perfectly.

Sorry for that Boomer, this video shows machine working with my fix

This is the related issue https://github.com/Slimefun-Addon-Community/Supreme/issues/52#issuecomment-2510464570, without the fix

**Comment by Boomer-1** [comment]
i still am not having any issues moving items in or out of any of the supreme machines. i think maybe your expectations of what the machine does, doesn't match what it's actually doing. i have no problem creating any resources at all. for networks, to move items from any machine, regardless of the addon, they must first go to a storage of some sort. networks cannot move from machine to machine

**Comment by Boomer-1** [comment]
the original issue that you referenced back to has already been fixed

**Comment by scorninpc** [comment]
Is this expected? Is this how the machine is supposed to work? Shouldn't it fill all 9 slots with cobblestone?


https://github.com/user-attachments/assets/39185bbb-8221-49c6-a5eb-968039cc1207

**Comment by Boomer-1** [comment]
it has never filled all 9 slots for that particular instance. it starts working when the first stack goes in. the 9 slots are for those recipes that require 9 different items. even items that are used more than 1 time in the recipe don't need multiple slots.

**Comment by scorninpc** [comment]
I think you need to see what PR 70 do

Anyway, thank you for your attention

**Pull request closed without merging**
