### PR TITLE
Fix Misspellings & Improve Performance

### PR DESCRIPTION
**Pull request by JustAHuman-xD**
This PR basically replaces #37 
Helps with #36 
The tech generator performance issue is not as easy to solve as most of the problems areas are essential to the machine and are laggy from slimefun method calls.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
All of this is untested atm, if anyone else wants to test it that would be appreciated, but I will be able to test it whenever I get home.

**Comment by RelativoBR** [comment]
I'm testing the change, if there was any problem in their operation, but part of the large-scale development, I can't validate

**Comment by JustAHuman-xD** [comment]
Did you test that using mob tech properly changed everything?

**Comment by RelativoBR** [comment]
I tested the 3 machines with different tier and types, they worked correctly.

**Comment by SrMonsterYT** [comment]
lag tripled in version #25 supreme

version supreme #23 -> https://prnt.sc/2snKITZHsMC4
version supreme #25 -> https://prnt.sc/mWR7vm7wOqb9

timings paper: https://timings.aikar.co/dev/?id=bd1a2c9d88b34f72b2eeb89069bb6c1c

timings spark: https://spark.lucko.me/d8tUnWFBSx

**Comment by JustAHuman-xD** [comment]
Try with the new version, lag should be le gone

**Comment by SrMonsterYT** [comment]
> Try with the new version, lag should be le gone

there is still a problem in supreme, see

timings paper: https://timings.aikar.co/dev/?id=610ae37862014835a87df55eb59fc430
spark timings: https://spark.lucko.me/w76fiWIMTG


image 1: https://prnt.sc/5SWy-Meyadto
image 2: https://prnt.sc/iMG9mFUeBuRo

my slimefun always stays at 20% in plugins when i update supreme it stays between 60% - 67% i don't know what's going on but these updates in supreme increased the performance a lot

**Pull request merged**
